### ISSUE TITLE
hello，about bigger sizes input?

### ISSUE THREAD

**Issue by 1448643857** [lmartak/distill-nn-tree#5]
First of all, thank you for such a good code. I want to ask, when I input a larger size, such as 224 * 224 * 3, I find that the training has no effect, is it necessary to change some parts of the code?

**Comment by lmartak** [comment]
Yes, some changes were necessary. I just pushed them via [this commit](https://github.com/lmartak/distill-nn-tree/commit/cab9943fecde1bdcbeffd0cc3ed038521790ec77). You should now be able to use both the `ConvNet` model and `draw_tree` routine with multi-channel images as well (TreeModel was already agnostic as it uses flattened inputs). See the changes in the MNIST notebook for usage (`img_chans` now needs to be specified as extra parameter). Image resolution (height x width) is already specifiable, so no updates were needed there.
